Import('env')

env.RunTests(PLUGIN_ARGS=('-mem2reg', '-no-pointer-arithmetic', '-mem2reg','-redef','-sra', '-find-length', 
'-annotator', '-debug', '-annotator-output', 'output.json'), TEST='annotator')
