Import('env')


########################################################################


# compile C source to LLVM bitcode
source = File('iiglue-reader-peek.c')
bitcode = env.BitcodeBinary(source)

# run IIGlueReader to read saved iiglue output
json = source.target_from_source('', '.json')
plugin = env.File('../${LIBPREFIX}IIGlueReader${SHLIBSUFFIX}')
actual = source.target_from_source('', '.actual')
env.Command(
    actual, (plugin, json, bitcode),
    [
        [
            'opt',
            '-analyze', '-o', '$TARGET',
            '-load', '${SOURCES[0].abspath}',
            '-iiglue-reader', '-iiglue-read-file', '${SOURCES[1]}',
            '${SOURCES[2]}',
        ],
    ],
)

# compare IIGlueReader output dump to expected output
env.Expect(actual)


########################################################################


# convenient "scons test" alias to run all tests
Alias('test', Glob('*.passed'))


# Local variables:
# flycheck-flake8rc: "../scons-flake8.ini"
# End:
