Import('env')

env.RunTests(PLUGIN_ARGS=('-mem2reg', '-null-argument-annotator', '-debug-only=find-sentinels-helper', '-output', 'output.json'))
#SConscript(dirs=['whole-program-tests'], exports='env')
