Import('env')

env.RunTests(PLUGIN_ARGS=('-instnamer', '-mem2reg', '-break-crit-edges', '-vssa', '-find-length'))


#SConscript(dirs=['range-analysis-fun', 'symbolicRangeFun'], exports='env')
SConscript(dirs=['symbolicRangeFun'], exports='env')