########################################################################
#
#  common imports and setup for all tests
#

Import('env')


########################################################################
#
#  NullAnnotator tests
#

sources = Glob('*.c')
for source in sources:
    # compile C source to LLVM bitcode, then analyze using iiglue
    bitcode = env.BitcodeSource(source)
    json = source.target_from_source('json/', '.json') 
    env.IIGlueAnalyze(json, bitcode)
    actual = source.target_from_source('actualsAndExpecteds/', '.actual')
    env.RunPlugin(actual, (bitcode, json), PLUGIN_ARGS=('-mem2reg', '-null-annotator'))

    # compare output dump to expected output
    env.Expect(actual)


########################################################################
#
#  common post-setup work for all tests
#

# convenient "scons test" alias to run all tests
Alias('test', Glob('actualsAndExpecteds/*.passed'))


# Local variables:
# flycheck-flake8rc: "../scons-flake8.ini"
# End:
