Import('env')

env.RunTests('-find-struct-elements', '--fast=false')

########################################################################
#
#  subdirectories
#

SConscript(dirs=['interproceduralTests'], exports='env')

# Local variables:
# flycheck-flake8rc: "../scons-flake8.ini"
# End:
