Import('env')

env.RunTests(
    PLUGIN_ARGS=(
        '-mem2reg', '-no-pointer-comparisons', '-dce', '-mem2reg', '-redef',
        '-sra-annotator',
        '-annotator', '-debug-only', '-find-length'
    ),
    TEST='annotator',
)

########################################################################
#
#  subdirectories
#

SConscript(dirs=['interprocedural'], exports='env')

# Local variables:
# flycheck-flake8rc: "../scons-flake8.ini"
# End:
