########################################################################
#
#  common imports and setup for all tests
#

Import('env')

testDir = Dir('.')
plugin = env['plugin']


########################################################################
#
#  FindSentinels tests
#

sources = Glob('*.c')

for source in sources:

    # compile C source to LLVM bitcode, then analyze using iiglue
    bitcode = env.BitcodeSource(source)
    json = source.target_from_source('json/', '.json') 
    env.IIGlueAnalyze(json, bitcode)

    actual = source.target_from_source('actualsAndExpecteds/', '.actual')
    env.RunPlugin(actual, (bitcode, json), PLUGIN_ARGS=('-mem2reg', '-find-sentinels'))

    # compare output dump to expected output
    env.Expect(actual)


########################################################################
#
#  subdirectories
#

SConscript(dirs='interproceduralTests', exports='env')

########################################################################
#
#  common post-setup work
